name: Main Workflow

on:
  push:
    branches: [main]

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"
        
      - name: Build
        run: |
          npm install
          ncc build src/index.ts

      - name: Test
        run: npm test
